---
name: CI
on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - run: |
          python -m venv .venv
          .venv/bin/pip install -r requirements-dev.txt
          .venv/bin/python -m pytest tests/

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
          architecture: x64

      - run: |
          python -m venv .venv
          .venv/bin/pip install -r requirements-dev.txt
          .venv/bin/python -m coverage run --source=pyairnow -m pytest tests

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
          architecture: x64

      - run: |
          python -m venv .venv
          .venv/bin/pip install -r requirements-dev.txt
          .venv/bin/flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          .venv/bin/flake8 --count --exit-zero --max-complexity=12 --max-line-length=127 --statistics
